### ISSUE TITLE
Does not install in .NET 4.5.1

### ISSUE THREAD

**Issue by premy** [chrispaynter/firebase-auth-dotnet#1]
Nuget Console err msg (translated from PT-BR)
Install-Package : Not possible to install package 'Firebase.Auth.Rest 1.1.8-beta'. You're trying to install this package in a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly reference or content file that's compatible with this structure.

**Comment by chrispaynter** [comment]
Sorry for this rather late reply. I've been in need of the library and have returned to update it.

Yes sorry I didn't add support for .NET framework.

If needed still, you could create a PR to include support.

I'll close this now considering the age of the issue.
